version: "2.1"

services:
  cli:
    environment:
      - PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}

# PHPMyAdmin
  adminer:
    image: adminer
    labels:
      - io.docksal.virtual-host=adminer.${VIRTUAL_HOST}